### PR TITLE
Add locales

### PR DESCRIPTION
**Pull request by dgmora**
This is just a brief setup, not the translations.
- If you go to /, english is shown
- Same if you go to /en
- If you go to /es, Spanish translation is shown (the one I added, we can just remove it and use german)
- The locale is kept between requests (thanks to `ApplicationController#default_url_options` and `ApplicationController#before_action`. You can give it a try by going to Register/Login from the root page.

There is no frontend and just a few translations added. I didn't add it because it takes a lot of time, and if the frontend will be changed soon, there's not a lot of value translating the views at the moment.

Also added a test

### CODE REVIEW

**Comment by ninabreznik** [comment]
Yay, this sounds awesome. I will check it out later tonight. Thanks a lot :)

On 25th June there will be a hackathon and our project will be also there so would be super if you could join http://codefor.de/digitalrefugeelabs/

**Comment by ninabreznik** [comment]
Aloha, @dgmora! I merged the code. Can you give me few instructions how to continue from here? We would need some dropdown to select language, I guess and then we just have to add more translations, right?

Very happy for that, btw. This was hanging above our heads for a long time (:

**Comment by ninabreznik** [comment]
Ok, ok, I see it now. So dropdown or flags or whatever we choose should link to /en or /es etc. And we have one yaml also for static pages. Looks great. Have to change some text already and when I finalise it, we can start translating. 👍

**Comment by dgmora** [comment]
Yes, so you can put a dropdown or flags in the header with a link to the same page, sending the locale symbol: `:en, :de`, whatever. You also need to add the available locales in `application.rb`.

About the translations: If you follow the same structure in the yaml as in your files, you can use "shortcuts". Example:
From:
`static_pages/welcome.html.erb`
Normally you would access the translation of the title as `static_pages.welcome.title`, but as the structure is the same (`static_pages` and `welcome`), you can use a shortcut and use just `.title`. I would follow the same structure as in the files for the yamls. The exception might be, for some texts that are repeated across different files.

**Pull request closed without merging**
